# Generated by Django 4.2.6 on 2023-11-30 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('idCity', models.CharField(max_length=3, primary_key=True, serialize=False, verbose_name='idCity')),
                ('name', models.CharField(max_length=25, verbose_name='CityName')),
                ('idcountry', models.CharField(max_length=3, verbose_name='idCountry')),
                ('district', models.CharField(max_length=25, verbose_name='NameOfCity')),
                ('population', models.BigIntegerField(verbose_name='Population')),
                ('idTownHall', models.CharField(max_length=3, verbose_name='townhallid')),
            ],
            options={
                'verbose_name': 'Name City',
                'verbose_name_plural': 'Name Citys',
                'ordering': ['name'],
                'unique_together': {('name', 'idcountry')},
            },
        ),
    ]
