# Generated by Django 4.2.6 on 2023-11-30 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TownHall',
            fields=[
                ('id_townhall', models.CharField(max_length=3, primary_key=True, serialize=False, verbose_name='idTownHall')),
                ('mayor', models.CharField(max_length=25, verbose_name='Mayor name')),
                ('councillor', models.CharField(max_length=25, verbose_name='active')),
            ],
            options={
                'verbose_name': 'Name TownHall',
                'verbose_name_plural': 'Name TownHalls',
                'ordering': ['id_townhall'],
                'unique_together': {('id_townhall', 'mayor')},
            },
        ),
    ]
